review component added
microservices-course-itmo/wineup-web pull request #11
Opened 2020-10-25 13:31 UTC by ptangra

@MarkSmirnov13 @alexstrive

2020-10-25 13:32 UTC, alexstrive approved these changes

2020-11-03 10:46 UTC, MarkSmirnov13 requested changes

2020-11-03 10:46 UTC, MarkSmirnov13 commented on components/ReviewCard.js
> +
Убери пожалуйста лишние отступы

2020-11-03 10:46 UTC, MarkSmirnov13 commented on components/ReviewCard.js
> +        elements.push(<text>{text}</text>)
Используй тег `<p>`

2020-11-03 10:46 UTC, MarkSmirnov13 commented on components/ReviewCard.js
> +        elements.push(<text>{text}.</text>)
Используй тег `<p>`

2020-11-03 10:46 UTC, MarkSmirnov13 commented on components/ReviewCard.js
> +          <text>{logDate}</text>
Используй тег `<p>`

2020-11-03 10:46 UTC, MarkSmirnov13 commented on components/ReviewCard.js
> +          <text className='textBtn'>{btnText}</text>
Используй тег `<p>`

2020-11-03 10:46 UTC, MarkSmirnov13 commented on components/ReviewCard.js
> +          {starsNumber.map((star, index) => (
Вместо startsNumber лучше используй `Array.from({ length: 5 })`

2020-11-03 10:46 UTC, MarkSmirnov13 commented on .storybook/styles.css
>    font-style: normal;
Добавь плиз компонент в сторибук

2020-11-09 09:24 UTC, MarkSmirnov13 approved these changes

2020-11-09 09:25 UTC, merged