added Favorites page
microservices-course-itmo/wineup-web pull request #24
Opened 2020-11-22 17:17 UTC by ptangra

@alexstrive @MarkSmirnov13

2020-11-22 17:18 UTC, alexstrive approved these changes

2020-11-23 11:47 UTC, MarkSmirnov13 requested changes
Нет верстки кнопки "Посмотреть больше"

Попробуй сделать сортировку карточек с винами по кнопкам и очистку избранного

2020-11-23 11:47 UTC, MarkSmirnov13 commented on components/CatalogFavorite.js
> +          margin-left: 35px;
Зачем это здесь?

2020-11-23 11:47 UTC, MarkSmirnov13 commented on components/CatalogFavorite.js
> +          gap: 45px;
на макете gap другой

2020-11-23 11:47 UTC, MarkSmirnov13 commented on components/CatalogFavorite.js
> +          justify-content: center;
на макете карточки располагаются по умолчанию не по центру, а слева направо

2020-11-23 11:47 UTC, MarkSmirnov13 commented on pages/favorites.js
> +          {favorites.filter(({ isLiked }) => isLiked).length ? (
Если `favorites === undefined`, то будет ошибка
Добавь `favorites &&` перед этим

2020-11-23 11:47 UTC, MarkSmirnov13 commented on pages/favorites.js
> +        {!favorites.filter(({ isLiked }) => isLiked).length ? (
Если `favorites === undefined`, то будет ошибка
Добавь `favorites &&` перед этим

2020-11-23 11:47 UTC, MarkSmirnov13 commented on pages/favorites.js
> +              {favorites.map(item => (
Если `favorites === undefined`, то будет ошибка
Добавь `favorites &&` перед этим

2020-11-23 11:47 UTC, MarkSmirnov13 commented on pages/favorites.js
> +              <button
Делай ссылку через встроенный в next компонент `Link` (посмотри routing + router в next)

2020-11-23 11:47 UTC, MarkSmirnov13 commented on pages/favorites.js
> +          background-image: url('assets/heart-background.png');
картинка не того цвета

2020-11-23 11:47 UTC, MarkSmirnov13 commented on pages/favorites.js
> +        .emptyFavorite {
элемент спозиционирован не как на макете

2020-12-05 18:15 UTC, MarkSmirnov13 approved these changes

2020-12-05 18:15 UTC, merged