Created search text field with buttons and event handlers for them.
microservices-course-itmo/wineup-web pull request #3
Opened 2020-09-28 00:59 UTC by Fwerfad

2020-10-06 09:49 UTC, MarkSmirnov13 requested changes
Измени плез все png картинки на svg
В png качество картинки совсем очень не очень

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +import React from 'react'
В next js не нужно импортировать React

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +import React from 'react'
Сделай название файла с большой буквы, тк компонент)

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +            alt='city-icon.png'
Перепиши плиз на более понятный пользователю alt

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +            alt='heart.png'
Перепиши плиз на более понятный пользователю alt

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +        <div className='tittle'>
title))))))

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +            alt='man.png'
Перепиши плиз на более понятный пользователю alt

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +            margin: 10px 10px 10px 10px;
можно просто `margin: 10px;`

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +          .tittle {
title)))))000)))

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +            className='city-icon'
почему класс называется city-icon? Давам мб тогда сделаем просто общий класс .icon?

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +            .header {
давай тут лучше заюзаем `display: none;`

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/header.js
> +    <div>
А зачем тут нужен лишний div?

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +import React from 'react'
В next js не нужно импортировать React
Исправь название компонента просто на Search

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +        className='search-field-2'
Что такое search-field-2? Зачем 2 инпута?

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +            margin: 10px 10px 10px 10px;
margin: 10px;

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +            .search-field-1 {
display: none

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +              border-radius: 20px 20px 20px 20px;
border-radius: 20px;

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +        className='search-field-2'
Видимо второй input используется для адаптива в мобильной версии? А почему решил использовать 2 интпута, а не один?)

2020-10-06 09:49 UTC, MarkSmirnov13 commented on components/search-component.js
> +              height: 0px;
display: none

2020-10-06 12:38 UTC, Fwerfad commented on components/search-component.js
> +        className='search-field-2'
потому что плейсхолдер не в стилях, ну или я чего-то не знаю?)

2020-10-11 11:12 UTC, Fwerfad commented on components/search-component.js
> +        className='search-field-2'
Если можно как-то поменять плейсхолдер через css, то могу переделать

2020-10-11 13:10 UTC, MarkSmirnov13 commented on components/search-component.js
> +        className='search-field-2'
Можно поменять placeholder через js
Подписываешься на событие **resize** и в зависимости от пропсы **.innerWidth** меняешь значение placeholder'а

2020-10-12 12:10 UTC, Fwerfad commented on components/search-component.js
> +        className='search-field-2'
Я убрал плейсхолдер, без него лучше выглядит.

2020-10-12 12:51 UTC, MarkSmirnov13 approved these changes

2020-10-12 12:51 UTC, merged