Editable profile for user
microservices-course-itmo/wineup-web pull request #36
Opened 2021-02-28 15:31 UTC by lerese58

https://trello.com/c/lywKGaEX/40-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C

2021-03-01 20:08 UTC, MarkSmirnov13 requested changes
Смержи мастер

2021-03-01 20:08 UTC, MarkSmirnov13 commented on pages/profile/Profile.js
> +                <img className='avatar' src='/assets/user.svg' alt='user-pic' />
Напиши читаемый alt, можно что то вроде _User Picture_

2021-03-01 20:08 UTC, MarkSmirnov13 commented on pages/profile/Profile.js
> +    console.log(res.json())
зачем нужен `res`?

2021-03-01 20:08 UTC, MarkSmirnov13 commented on pages/profile/Profile.js
> +    console.log(res.json())
console.log не используем в ПР

2021-03-01 20:08 UTC, MarkSmirnov13 commented on pages/profile/Profile.js
> +                  alt='edit'
Edit с большой буквы

2021-03-01 20:08 UTC, MarkSmirnov13 commented on pages/profile/Profile.js
> +  const editedUser = {}
используй useState

2021-03-02 12:32 UTC, StanislavMyakishev commented on pages/profile/Profile.js
> +                  text={user.name}
Мы используем много полей из `user`, я думаю лучше выносить это в деконструкцию наверх, чтобы каждый раз не писать `user.`
```javascript
const { name, cityName, phoneNumber, ... } = user; 
```

2021-03-02 12:32 UTC, StanislavMyakishev commented on pages/profile/Profile.js
> +                    onInputChange('name', evt.currentTarget.value)
Может тут лучше передавать в функцию event, и раскрывать его внутри? На случай, если его логика изменится, лучше исправлять в одном месте, чем во всех местах использования :)

2021-03-02 12:38 UTC, StanislavMyakishev commented on pages/profile/Profile.js
> +  const onSubmit = async () => {
Из кода не очень понял сабмите изменений происходит обновление данных в инпутах: формы нет, так что страница не обновляется, здесь мы зайдем в useEffect и запросим новые данные?

2021-03-02 12:55 UTC, StanislavMyakishev requested changes
Есть несколько спорных мест, тегни как посмотришь :)

2021-03-02 15:00 UTC, lerese58 commented on pages/profile/Profile.js
> +                  text={user.name}
@StanislavMyakishev, в принципе согласен, но думаю и так нормально, ибо есть editedUser еще, слово user довольно короткое

2021-03-02 15:01 UTC, lerese58 commented on components/CustomInput/CustomInput.js
> +const CustomInput = ({ id, label, defaultValue, onChange }) => {
Превратности рефакторинга)) уже поправил

2021-03-02 15:03 UTC, lerese58 commented on pages/profile/Profile.js
> +                    onInputChange('name', evt.currentTarget.value)
Если это не критично, то пока оставлю так -- боюсь, что застряну

2021-03-03 17:07 UTC, MarkSmirnov13 approved these changes

2021-03-03 17:08 UTC, merged