rework wine position page
microservices-course-itmo/wineup-web pull request #37
Opened 2021-02-28 15:47 UTC by heyllog

2021-03-01 19:51 UTC, MarkSmirnov13 requested changes
Смержи мастер, а так слайдер красивый)

2021-03-01 21:50 UTC, heyllog commented
@MarkSmirnov13 смерджил)

2021-03-02 13:09 UTC, StanislavMyakishev requested changes

2021-03-02 13:09 UTC, StanislavMyakishev commented on components/SameWines/SameWines.js
> +          imageSrc='https://s3.winestyle.ru/images_gen/150/150258/0_0_orig.jpg'
Может придумаем как хранить такие ссылки на другие изображения в другом месте, а не прям так в коде? Или это пока просто для примера?

2021-03-02 13:09 UTC, StanislavMyakishev commented on components/SameWines/SameWines.js
> +        <WineCard
Тут много раз используется одна и та же конструкция с `<WineCard` и мне кажется, что аккуратнее бы смотрелось бы с рендерингом в цикле
```typescript
const sampleWinesList = [{
    wineId='796cf569-66bf-45f0-8635-1bb5720aee1d',
    imageSrc='https://amwine.ru/upload/iblock/3b5/3b59b74d1fd1e3b83f578e1544f2a5cf.png',
    info: {...},
    isLiked: true,
    color: 0,
}, ...]
...
{sampleWinesList.map(wineData => (
    <SwiperSlide>
        <WineCard {...wineData}/>
    </SwiperSlide>
)}
```
Я думаю должно сильно сократить количество кода и всё упростить)

2021-03-02 13:53 UTC, heyllog commented on components/SameWines/SameWines.js
> +          imageSrc='https://s3.winestyle.ru/images_gen/150/150258/0_0_orig.jpg'
Это просто для примера

2021-03-02 13:54 UTC, heyllog commented on components/SameWines/SameWines.js
> +        <WineCard
Это временная конструкция, исключительно для демо показа, потом данные будут браться с бэка

2021-03-02 19:39 UTC, MarkSmirnov13 approved these changes

2021-03-02 20:49 UTC, StanislavMyakishev approved these changes

2021-03-03 15:17 UTC, merged