Deploy gh pages
microservices-course-itmo/wineup-web pull request #39
Opened 2021-02-28 17:18 UTC by ptangra

@MarkSmirnov13

2021-03-01 19:27 UTC, MarkSmirnov13 requested changes

2021-03-01 19:27 UTC, MarkSmirnov13 commented on .github/workflows/gh-pages.yml
> +      - deply-gh-pages
Не забудь исправить здесь на `master`

2021-03-01 23:21 UTC, ptangra commented
@MarkSmirnov13

2021-03-02 06:20 UTC, ptangra commented on .github/workflows/gh-pages.yml
> +      - deply-gh-pages
Done👍

2021-03-02 08:40 UTC, MarkSmirnov13 requested changes

2021-03-02 08:40 UTC, MarkSmirnov13 commented on next.config.js
> +const pathPrefix = process.env.NODE_ENV === 'production' ? '/wineup-web' : ''
Этот файл не нужен, если хочешь завести константу - лучше создай файл constants.js и положи переменную туда

2021-03-02 08:40 UTC, MarkSmirnov13 commented on components/AuthorizationForm/AuthorizationForm.js
> +const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ''
Где ты задаешь данную .env переменную?
Ты точно для всех иконок добавил префикс?

2021-03-02 10:42 UTC, ptangra commented on components/AuthorizationForm/AuthorizationForm.js
> +const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ''
В gh-pages.yml. Думаю для всех добавил да.
@MarkSmirnov13

2021-03-02 10:45 UTC, ptangra commented on next.config.js
> +const pathPrefix = process.env.NODE_ENV === 'production' ? '/wineup-web' : ''
assetPrefix настрайваю там @MarkSmirnov13

2021-03-02 12:54 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ''
С префиксом вроде всё круто, но разве проверка на `|| ''` не лишняя? Или может быть так, что собралось без энва?

2021-03-02 12:57 UTC, ptangra commented on components/AuthorizationForm/AuthorizationForm.js
> +const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ''
Да чтобы локально тоже работало

2021-03-02 15:50 UTC, MarkSmirnov13 approved these changes

2021-03-02 20:46 UTC, StanislavMyakishev approved these changes

2021-03-03 17:30 UTC, merged