Add custom 404 page
microservices-course-itmo/wineup-web pull request #41
Opened 2021-02-28 21:18 UTC by lerese58

https://trello.com/c/XOJOMvYm/52-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-404

2021-03-01 19:26 UTC, MarkSmirnov13 requested changes

2021-03-01 19:26 UTC, MarkSmirnov13 commented on pages/404/404.js
> +              Попробуйте найти на <a href='/'>главной странице</a>
Используй компонент `Link` из `'next/link'`

2021-03-02 12:46 UTC, StanislavMyakishev commented on pages/404/404.js
> +          .description > p > a {
И если поменяешь на next/Link, то тут наверное лучше поменять класснейм на description-link и повесить его на сам линк + прикольно было бы сделать, чтобы подчёркивание появлялось при ховере, но это на твоё усмотрение
```typescript jsx
 <Link className="description-link">главной странице</Link>
...
.description-link {
    cursor: pointer; // если курсор меняется, то не добавлять)
    text-decoration: none;
}
.description-link:hover {
    text-decoration: underline;
}
```

2021-03-03 11:49 UTC, lerese58 commented on pages/404/404.js
> +          .description > p > a {
У Link нет className, селектор оставлю старый
Есть вариант еще: обернуть Link вокруг <a><a />

2021-03-03 16:14 UTC, MarkSmirnov13 approved these changes

2021-03-03 16:14 UTC, merged