Wineup web 49
microservices-course-itmo/wineup-web pull request #42
Opened 2021-02-28 21:21 UTC by Fwerfad

2021-03-01 19:17 UTC, MarkSmirnov13 requested changes
Используйте везде пожалуйста новое api. Почему в итоге пришли к решению не разделять компонент на более малкие?

2021-03-01 19:17 UTC, MarkSmirnov13 commented on components/AuthorizationForm/AuthorizationForm.js
> +        const response = await fetch(
Используйте api плиз

2021-03-02 13:50 UTC, StanislavMyakishev requested changes
Вообще, большая часть правок уйдет, если сделать как предложил Марк - разделить эту форму на большее число компонент - тогда и перечисление форм уйдет и храниться всё будет в небольших стейтах внутри компонент)

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +/* eslint-disable */
Я понимаю, что с eslint сложно в этом файле, но такая правка не может быть вмержена(
![meme](https://user-images.githubusercontent.com/37376899/109653332-f82aaf80-7b71-11eb-9ddd-82f6f15ce53e.jpg)

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +const pI = value => {
Нэйминг функции совсем непонятный, может что-то типа parseIntToDecimal будет лучше, но вообще лучше подумай над тем что ещё можно вынести в неё, если можно и стоило ли вообще это делать

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +            payload: `Ошибка: дней не может быть больше ${DAY_LIMIT}`,
Такие ошибки лучше хранить не как строки, а в объектах, так их можно будет легко менять + будет понятно по работе с кодом откуда какая ошибка 
```javascript
const CalendarErrors = {
    dayLimitExceeded: `Ошибка: дней не может быть больше ${DAY_LIMIT}`,
    ...
}
```

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +      const dateParts = date.split('.')
Тут, кажется, возможно сделать такую же конструкцию, что и в другом месте, тогда не придется писать `dateParts[0]`)
```javascript
const [day, month, year] = date.split('.')
```

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +              date.length === DAY_MAX_LENGTH ||
Здесь 3 вложенных `if`можно заменить одним, но более сложной проверкой, чтобы сделать её читаемой, на мой взгляд, нужно примерно следующе
```javascript
const isLastCharValid = date.charAt(date.length - 1) !== '.'
const isDateValid = date.length === DAY_MAX_LENGTH || date.length === DAY_PLUS_MONTH_MAX_LENGTH // тут посмотри почему ты сравниваешь DAY_max_length с DATE.length
const isDayValid = dateParts[0].length === 2 // тут, было бы круто поменять на day.length === 2
if (isLastCharValid && isDateValid && isDayValid)....
```

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +      if (day.length <= DAY_MAX_LENGTH) {
Здесь (и во всех аналогичных местах) можно очень просто сократить вложенность)
```javascript
if (day.length > DAY_MAX_LENGTH) return
...
```

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
>    const handleMonth = useCallback(
У нас получаются 3 функции с почти одинаковой функциональностью, которую можно решить пробрасыванием типа из инпута, размер и сложность функции немного увеличатся, но зато будет одна функция `handleCalendarChanges` а не три одинаковые)
Как должно выглядеть пробрасывание типа из инпута:
```javascript
// должно быть где и остальные константы
const inputType = {
   date: 'date',
   month: 'month',
   year: 'year',
}
...
<input
    className='inputField
    placeholder='ДД.ММ.ГГГГ'
    value={formState.date}
    onChange={() => handleDate(inputType.date}
/>
```

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +        username.length < USERNAME_MIN_LENGTH ||
Здесь кажется, что условие можно сократить)
```javascript
USERNAME_MIN_LENGTH < username.length < USERNAME_MAX_LENGTH
```

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
>          const format = /[ `1234567890№!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?~]/
Регулярки было бы прикольно вынести наверх к константам - так мы уберем лишнюю логику из функции
И назвать можно как-нибудь так: 
`const usernameRegex = ...`
`const phoneRegex = ...`

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +          `Error occurred during singing in with phone number: ${err}`
Я думаю, что подразумевалось`signing in`, а не `singing in` 🤣
и немнго странно, что все ошибки на русском, а эта на Английском

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +  const handleSecondForm1 = async () => {
Название не самое информативное, мне кажется, что нужно для управления разными видами форм использовать названия, а не integer, тут мы особо по памяти не проиграем, зато будет понятно что к чему.
```javascript
const formTypes = {
   phoneLoginForm: 'phoneLoginForm', 
   ....
}
```
После этого можно и переименовать остальные функции по типу этой)

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +            setAccessToken[1](json.accessToken)
Тут не должно быть [1] - не заметил, когда вчера правил)

2021-03-02 13:50 UTC, StanislavMyakishev commented on components/AuthorizationForm/AuthorizationForm.js
> +              value={formState.telephone}
И тут все повторения `formState` уйдут, если развернуть наверху
```javascript
const { telephone, telephoneError, ...} = formState;
```

2021-03-02 13:56 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +/* eslint-disable */
это временно

2021-03-02 13:56 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +/* eslint-disable */
а вообще давно починить линтер, за что console.log() ?

2021-03-02 14:02 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +            payload: `Ошибка: дней не может быть больше ${DAY_LIMIT}`,
Звучит неплохо, запишу на следующую стадию рефакторинга

2021-03-02 14:02 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +const pI = value => {
Переименовал в  parseIntToDecimal, как ты и попросил

2021-03-02 14:04 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +              date.length === DAY_MAX_LENGTH ||
Я кажется уже это делал, по крайней мере часть с [day, month, year], видимо кто-то это перетёр

2021-03-02 14:10 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
>          const format = /[ `1234567890№!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?~]/
done

2021-03-02 14:10 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +          `Error occurred during singing in with phone number: ${err}`
Очевидно, что это не я писал
Поправил

2021-03-02 14:14 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +  const handleSecondForm1 = async () => {
возьму на заметку на будущее

2021-03-02 14:14 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +            setAccessToken[1](json.accessToken)
поправил

2021-03-02 14:17 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +              value={formState.telephone}
Не совсем понял, что ты имеешь в виду, из формстейта достать переменные что ли?
А зачем тогда везде подставлял сам.. 
возьму на заметку

2021-03-03 16:12 UTC, Fwerfad commented on components/AuthorizationForm/AuthorizationForm.js
> +        const response = await fetch(
Поправил, но api не работает.

2021-03-10 07:01 UTC, StanislavMyakishev requested changes

2021-03-10 14:49 UTC, Fwerfad commented on components/AuthorizationForm/Calendar.js
> +  const handleMonth = useCallback(
получается, три спринта рефакторинга

2021-03-10 16:29 UTC, StanislavMyakishev approved these changes

2021-03-10 16:31 UTC, merged