Feature/filter bar
microservices-course-itmo/wineup-web pull request #5
Opened 2020-10-05 17:05 UTC by lerese58

add filter bar with custom checkbox
![_______________________________2020-10-03_02-09-14](https://user-images.githubusercontent.com/44510727/95109998-0a7cfa80-0746-11eb-8586-fb24b7934124.png)

2020-10-06 11:57 UTC, MarkSmirnov13 requested changes

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/CustomCheckBox.js
> +import React from 'react'
Реакт импортиться по умолчанию, эта строчка лишняя.

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/CustomCheckBox.js
> +            background-image: url("data:image/svg+xml,%3Csvg width='14' height='15' viewBox='0 0 14 15' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 9L6.5 14L13 1.5' stroke='white'
Попробуй все таки заюзать нормальную svg

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/FilterBar.js
> +const getCriteriaGroup = (criteria, mapObject) => {
Эта функция лишняя, просто перенести эту логику в компонент

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/FilterBar.js
> +import React from 'react'
Реакт импортиться по умолчанию, эта строчка лишняя.

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/FilterBar.js
> +      {/* eslint-disable-next-line react/button-has-type */}
Убери плиз eslint-disable, либо добавь новое правильно в эслинт конфиг

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/FilterBar.js
> +const FilterBar = ({ criteriaMap }) => {
А где у тебя хранится стейт формы? Его необходимо добавить, чтобы мы потом могли эти данные отправлять на сервер (либо фильтровать карточки прямо на фронте)

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/FilterBar.js
> +          <svg
Давай лучше вынесем svg в отдельный файл и будем вставлять изображения через тег `<img>`

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/InputContainer.js
> +        {/* <InputList hidden inputType={type} inputList={inputList} /> */}
а зачем эта закомменченная строчка?

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/InputContainer.js
> +          <svg
Давай лучше вынесем svg в отдельный файл и будем вставлять изображения через тег <img>

2020-10-06 11:57 UTC, MarkSmirnov13 commented on components/InputContainer.js
> +          className={open ? 'arrow-up' : 'arrow-down'}
У тебя почему то не прописан класс для `arrow-up`

2020-10-06 12:02 UTC, MarkSmirnov13 requested changes

2020-10-06 12:02 UTC, MarkSmirnov13 commented on components/FilterBar.js
> +        <InputContainer
Добавь еще сюда `key={придумай что сюда}`
Любой ребенок в компоненте лист должен иметь такой параметр
Еще как будешь это менять, проверь консоль, там есть еще ошибки.

2020-10-12 18:13 UTC, lerese58 commented on components/FilterBar.js
> +      {/* eslint-disable-next-line react/button-has-type */}
airbnb запрещает тип кнопки reset, добавлю правило

2020-10-15 13:39 UTC, lerese58 commented on components/FilterBar.js
> +const FilterBar = ({ criteriaMap }) => {
а разве форма не отправляет запрос?

2020-10-20 16:19 UTC, lerese58 commented
![image](https://user-images.githubusercontent.com/44510727/96614795-2f0dd080-1309-11eb-9c0e-8d6781149197.png)

2020-10-23 23:26 UTC, lerese58 commented
![image](https://user-images.githubusercontent.com/44510727/97061633-2d116f00-15a0-11eb-874e-f8a6589f6662.png)
![image](https://user-images.githubusercontent.com/44510727/97061670-461a2000-15a0-11eb-8178-cf0411709718.png)

2020-10-25 19:49 UTC, alexstrive approved these changes
Напомните, чтобы я спросил на созвоне про использование TypeScript, propTypes и defaultProps.

2020-11-02 15:55 UTC, MarkSmirnov13 approved these changes

2020-11-02 15:55 UTC, merged