Fixed favorites add/delete functions and loading wines on favorites page
microservices-course-itmo/wineup-web pull request #60
Opened 2021-03-14 20:18 UTC by ptangra

@MarkSmirnov13

2021-03-15 19:41 UTC, MarkSmirnov13 requested changes

2021-03-15 19:41 UTC, MarkSmirnov13 commented on components/WinePosition/WinePosition.js
> +              clickHeart(window.location.pathname.substring(6), accessToken)
мы никак не можем по другому получить название вина? Возможно пробросить его в качестве параметра из компонента выше? Сейчас выглядит не очень

2021-03-15 19:41 UTC, MarkSmirnov13 commented on pages/favorites.js
> +            // console.log(favorites)
удали этот коммент

2021-03-15 21:35 UTC, ptangra commented on components/WinePosition/WinePosition.js
> +              clickHeart(window.location.pathname.substring(6), accessToken)
Так как компонент выше переходить к этому компоненту по линку, вроде нельзя параметр передать. А так я думаю никаких проблемов не будет.

2021-03-15 21:35 UTC, ptangra commented on pages/favorites.js
> +            // console.log(favorites)
убрал

2021-03-17 14:07 UTC, MarkSmirnov13 commented on components/WinePosition/WinePosition.js
> +              clickHeart(window.location.pathname.substring(6), accessToken)
Если мы знаем линку, почему бы нам не взять от туда id и не передать в качестве параметра?

2021-03-17 15:36 UTC, MarkSmirnov13 commented
1. Когда у меня нет в избранно ничего, на главной странице все равно почему то некоторые вина отмечены как лайкнутые
2. Перехожу на страницу вина - нажимаю Добавить в избранное - перехожу в избранное - там ничего нет
С перезагрузкой страницы работает, но нужно сделать стейт локальный, чтобы работало и без перезагрузки
3. Кнопка Очистить избранное не работает
4. Если добавил вино в избранное - потом перешел на него - почему то отображается снова кнопка "добавить в избранное", хотя оно уже в избранном и должно быть "удалить из избранного"

2021-03-27 16:17 UTC, ptangra commented
@MarkSmirnov13

2021-03-31 10:39 UTC, ptangra commented
@MarkSmirnov13 посмотри пожалуйста

2021-03-31 17:12 UTC, MarkSmirnov13 approved these changes

2021-03-31 17:12 UTC, merged