Feature/notifications
microservices-course-itmo/wineup-web pull request #62
Opened 2021-03-15 16:23 UTC by lerese58

https://trello.com/c/LYYTe0vp/63-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B0-%D0%BD%D0%BE%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B9

2021-03-16 09:50 UTC, StanislavMyakishev requested changes

2021-03-16 09:50 UTC, StanislavMyakishev commented on components/Badge/Badge.js
> +const Badge = ({ count }) => {
Добавь, пожалуйста, коммент с типами пропсов, так если бэйдж будет расширяться мы не запутаемся в том, что нам сюда приходит)

2021-03-16 09:50 UTC, StanislavMyakishev commented on components/Header/Header.js
> +        isActive={activeImage === 'city'}
Добавишь что-то типа такого?)
```javascript
const MenuItemKeys = {
   city: 'city'
}
...
isActive={activeImage === MenuItemKeys.city}
```

2021-03-16 09:50 UTC, StanislavMyakishev commented on components/HeaderMenuItem/HeaderMenuItem.js
> +const HeaderMenuItem = ({
Классный компонент, давно нужно было это всё вынести) 
Здесь тоже не забудь добавить комменты по пропсам)

2021-03-16 09:50 UTC, StanislavMyakishev commented
Добавь, пожалуйста, скрины к ПРу, + не забудь записать демку того как это работает)

2021-03-19 16:13 UTC, lerese58 commented
@StanislavMyakishev ПР скучает без тебя((

2021-03-20 14:04 UTC, StanislavMyakishev approved these changes

2021-03-20 14:27 UTC, merged