web-wine-77
microservices-course-itmo/wineup-web pull request #70
Opened 2021-03-21 17:05 UTC by jnannni

Ссылка на задачу: https://trello.com/c/QMsGUrGe

2021-03-23 17:27 UTC, StanislavMyakishev approved these changes

2021-03-23 17:37 UTC, StanislavMyakishev commented
Тут конфликт в AuthorizationForm, поправишь?)

2021-03-24 17:03 UTC, MarkSmirnov13 commented
А откуда yarn.lock взялся?))

2021-03-24 17:03 UTC, MarkSmirnov13 requested changes
Удали пожалуйста yarn.lock

2021-03-24 17:15 UTC, MarkSmirnov13 approved these changes

2021-03-24 17:15 UTC, merged