add footer
microservices-course-itmo/wineup-web pull request #89
Opened 2021-04-03 21:25 UTC by heyllog

2021-04-04 19:51 UTC, MarkSmirnov13 requested changes

2021-04-04 19:51 UTC, MarkSmirnov13 commented on components/Footer/Footer.js
> +            <div className='nav-top'>
Классы договорились называть в camelCase

2021-04-04 19:51 UTC, MarkSmirnov13 commented on components/Footer/Footer.js
> +            <div className='nav-bottom'>
camelCase)

2021-04-04 19:51 UTC, MarkSmirnov13 commented on components/Footer/Footer.js
> +              <a href='/'>Возможности</a>
Сейчас все ссылки будут редиректить на '/',  давай пока мы не знаем куда они будут вести - они никуда не будут вести?)

2021-04-04 19:54 UTC, MarkSmirnov13 commented
А мы можем добавить `<Footer /> ` в _app.js чтобы не добавлять его на каждую страницу отдельно?

2021-04-04 20:25 UTC, heyllog commented on components/Footer/Footer.js
> +              <a href='/'>Возможности</a>
Ссылки в никуда не даёт сделать линтёр

2021-04-04 20:25 UTC, heyllog commented on components/Footer/Footer.js
> +            <div className='nav-top'>
ок

2021-04-04 20:25 UTC, heyllog commented on components/Footer/Footer.js
> +            <div className='nav-bottom'>
ок

2021-04-06 19:37 UTC, MarkSmirnov13 approved these changes

2021-04-07 07:46 UTC, merged