Confirm clear favorites
microservices-course-itmo/wineup-web pull request #91
Opened 2021-04-04 19:16 UTC by ptangra

@MarkSmirnov13

2021-04-04 19:30 UTC, MarkSmirnov13 approved these changes

2021-04-04 19:30 UTC, MarkSmirnov13 commented on components/ConfirmClearFavorites/ConfirmClearFavorites.js
> +    // eslint-disable-next-line
На что он сдесь ругается? Нужно исправить ошибку, eslint-disable не используем в проде

2021-04-04 19:30 UTC, MarkSmirnov13 commented on components/ConfirmClearFavorites/ConfirmClearFavorites.js
> +            margin-left: 250.81px;
У иконки прям такой отступ на макете?

2021-04-04 19:30 UTC, MarkSmirnov13 commented on components/CustomFormButton/CustomFormButton.js
> +  textColorOnHovor = '#af2f4e',
**textColorOnHover** )

2021-04-04 19:30 UTC, MarkSmirnov13 commented on components/CustomFormButton/CustomFormButton.js
> +          color: ${textColorOnHovor};
Тут тоже исправь

2021-04-04 19:30 UTC, MarkSmirnov13 commented on pages/ClearFavorite/ClearFavorite.js
> +import ConfirmClearFavorites from '../../components/ConfirmClearFavorites'
А зачем нужна эта страница? Нужно просто показать попап/модалку если пользователь хочет удалить избранное, отдельную страницу делать не надо

2021-04-04 19:30 UTC, MarkSmirnov13 commented on pages/favorites.js
> +            // onClick={() => clearFavorites()}
Забыл удалить коммент

2021-04-04 19:55 UTC, MarkSmirnov13 requested changes
Апрувнул поошибке)

2021-04-06 17:35 UTC, ptangra commented on components/ConfirmClearFavorites/ConfirmClearFavorites.js
> +    // eslint-disable-next-line
готово.

2021-04-06 17:36 UTC, ptangra commented on components/ConfirmClearFavorites/ConfirmClearFavorites.js
> +            margin-left: 250.81px;
убрано.

2021-04-06 17:38 UTC, ptangra commented on components/CustomFormButton/CustomFormButton.js
> +  textColorOnHovor = '#af2f4e',
найс. хах

2021-04-06 17:38 UTC, ptangra commented on components/CustomFormButton/CustomFormButton.js
> +          color: ${textColorOnHovor};
готово.

2021-04-06 17:41 UTC, ptangra commented on pages/ClearFavorite/ClearFavorite.js
> +import ConfirmClearFavorites from '../../components/ConfirmClearFavorites'
чтобы на background избранное было)

2021-04-06 18:12 UTC, ptangra commented on pages/ClearFavorite/ClearFavorite.js
> +import ConfirmClearFavorites from '../../components/ConfirmClearFavorites'
ладно забудь понял хах

2021-04-06 18:22 UTC, ptangra commented on pages/favorites.js
> +            // onClick={() => clearFavorites()}
да

2021-04-06 18:30 UTC, ptangra commented
@MarkSmirnov13 посмотри пожалуйста. В этом пр-е, кроме поп-ап очистить избранное я залил и фикс избранного. Все что эти тестировщики показывали уже исправлено.

2021-04-07 10:49 UTC, ptangra commented
@MarkSmirnov13 добавил второго поп-апа, посмотри.

2021-04-07 16:13 UTC, MarkSmirnov13 approved these changes

2021-04-07 16:13 UTC, merged